### ISSUE TITLE
Support for running the server in Docker

### ISSUE THREAD

**Issue by ajs1998** [motion-canvas/motion-canvas#188]
**Description**

Some people don't want to install and run node things manually. Docker would allow us to execute a single `docker run` command to get the server running and ready to use.

A user should be able to either:
1. Follow the guide, run `npm init @motion-canvas`, and follow the prompts like normal to create a new project
2. Use a `docker run` command to specify project config with environment variables to bypass the CLI prompts.

**Proposed solution**
Do everything the Getting Started guide with a `Dockerfile`. Here is an example of what it might look like.

```Dockerfile
FROM node:19

WORKDIR /app

# Fails because there is currently no way around the CLI prompts for project name, project path, and language
# These prompts should be skippable if you provide the values as environment variables
RUN npm init -y @motion-canvas && cd my-animation && npm install

CMD ["npm", "run", "serve"]

# TODO Use a volume to mount the project directory so it can be edited on the host machine
```

Then,

```bash
docker build -t "motion-canvas" .
docker run --name "motion-canvas" \
  -p "9000:9000" \
  -e "PROJECT_NAME=demo-animation" \
  -e "PROJECT_PATH=." \
  -e "PROJECT_LANGUAGE=ts" \
  -v "$(pwd)/app:/app" \
  motion-canvas
```

**Considered alternatives**
I don't think a `docker-compose.yml` makes sense for such a simple server, but correct me if I'm wrong here. Whatever makes it easiest for the end user to get something up and running is the goal.

**Additional context**
Would also be nice if this were integrated into GitHub Actions to publish the image to Docker Hub.

**Comment by TheNexter** [comment]
```
version: "3.8"
services:
  motion-canvas:
    image: motion-canvas
    container_name: motion-canvas
    environment:
      - PROJECT_NAME=demo-animation
      - PROJECT_PATH=.
      - PROJECT_LANGUAGE=ts
    volumes:
      - /path/to/data:/app
    restart: unless-stopped
```

Remplace :
  - The image name by your
  - Volume on host path by your

**Comment by miikkuu** [comment]
@aarthificial  should i go ahead solving this issue?

**Comment by aarthificial** [comment]
Yes, the issue is accepted, so go ahead. I'm a bit rusty when it comes to Docker, so I don't have any suggestions as to how to do this. Let me know if you'll need help with configuring the GitHub workflow though.

**Comment by guifeliper** [comment]
@miikkuu do you still working on it or can I take over?

**Comment by ajs1998** [comment]
@RuboGubo I'm pretty new to this project so I don't think I could be much help. Whoever has experience on the `npm init` CLI part should probably be involved in making sure environment variables can override the prompts. I think that's the biggest blocker.

**Comment by aarthificial** [comment]
After #668, it will be possible to provide answers using command-line arguments:
```sh
npm init @motion-canvas@latest -- --name Hello --path ./hello --language ts
```

**Comment by SleeklyCoding** [comment]
It's not a trivial thing as it looks like. 

When we execute `npm init` by `RUN` command, we will get package.json, node_modules, and other files during the build phase of an image.

When we decide to attach volumes to the running container (binding volumes) we will erase all downloaded data by npm init and install and we will get an error that '..package.json is not found...'

The solution would be to move `npm init && npm install && npm run` to `CMD` command.

The dependencies will be downloaded runtime and we will get them on the host side by attaching volume.

Dockerfile could look something like this:
```Dockerfile
FROM node:lts

WORKDIR /app

ENV PROJECT_NAME my-animation
ENV PROJECT_PATH ./my-animation

ENV PROJECT_LANGUAGE ts
ENV PROJECT_PLUGINS ffmpeg

CMD npm init -y @motion-canvas@latest -- --name $PROJECT_NAME --path $PROJECT_PATH --language $PROJECT_LANGUAGE --plugins $PROJECT_PLUGINS && cd $PROJECT_PATH && npm install -y && npm run serve -- --host 0.0.0.0 --port 9000

```

**Comment by jaun-van-heerden** [comment]
I've got a `docker-compose.yml` and a `.devcontainer` setup with two drawbacks: hot-reload not working and user permissions potentially not correct.

**`Dockerfile`**
```Dockerfile
FROM node:lts

# Install necessary tools
RUN apt-get update && apt-get install -y \
    curl \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

# Create app directory and set permissions
WORKDIR /app

# Set environment variables
ENV PROJECT_NAME=my-animation \
    PROJECT_PATH=./projects/my-animation \
    PROJECT_LANGUAGE=ts \
    PROJECT_PLUGINS=ffmpeg

# USER root

# Create projects directory and set permissions
RUN mkdir -p /app/projects && chmod 777 /app/projects

# Copy entrypoint script
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 9000

# USER node

ENTRYPOINT ["/entrypoint.sh"]
```


**`docker-compose.yml`**
```yaml


services:
  motion-canvas:
    build:
      context: .
      dockerfile: Dockerfile
    image: motion-canvas:latest
    working_dir: /app/projects
    container_name: motion-canvas
    environment:
      - PROJECT_NAME=my-animation
      - PROJECT_PATH=/app/projects/my-animation
      - PROJECT_LANGUAGE=ts
      - PROJECT_PLUGINS=ffmpeg
    ports:
      - "9000:9000"
    volumes:
      - ./projects:/app/projects
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  projects:

networks:
  default:
    name: motion-canvas-network

```


**`.devcontainer/devcontainer.json`**
```json
{
    "name": "Motion Canvas Development",
    "dockerComposeFile": "../docker-compose.yml",
    "service": "motion-canvas",
    "workspaceFolder": "/app",
    "customizations": {
        "vscode": {
            "extensions": [
                "dbaeumer.vscode-eslint",
                "esbenp.prettier-vscode",
                "ms-azuretools.vscode-docker"
            ],
            "settings": {
                "terminal.integrated.shell.linux": "/bin/bash"
            }
        }
    },
    "forwardPorts": [9000],
    "postCreateCommand": "/entrypoint.sh"
}
```
**`entrypoint.sh`**
```bash
#!/bin/bash
set -e

# Initialize the project if it doesn't exist
if [ ! -d "$PROJECT_PATH" ]; then
    npm init -y @motion-canvas@latest -- --name $PROJECT_NAME --path $PROJECT_PATH --language $PROJECT_LANGUAGE --plugins $PROJECT_PLUGINS
    cd $PROJECT_PATH
    npm install
else
    cd $PROJECT_PATH
    npm install
fi

# Start the development server
npm run serve -- --host 0.0.0.0 --port 9000

```

**Run with** `docker compose up -d` or open dev container in VSCode

---

What's nice is the inbuilt VSCode browser places everything in one window
