### ISSUE TITLE
Add an HTML overlay on top of the canvas to potentially add controls and extra info even in presentation mode

### ISSUE THREAD

**Issue by Gabryxx7** [motion-canvas/motion-canvas#825]
**Description**
As the title says, it would be nice to have the possibility to see some extra info even while presenting. I opted for a transparent HTML overlay which does not affect the canvas rendering at all and can display any sort of watermark, info, a progressbar or even a little panel with controls.

**Proposed solution**
As per my previous issue I have already implemented and tested this but I did too much on my own fork and I can't really send a PR with so many changes all together...
The solution is fairly easy but works great so far. There was already a `CustomStage` component, so I added an overlay component called [`CustomStageOverlay`](https://github.com/Gabryxx7/motion-canvas/blob/main/packages/ui/src/components/viewport/CustomStageOverlay.tsx), which can be added to the CustomStage as such:
```typescript
export function CustomStage({stage, forwardRef, children, keyPressed} : CustomStageProps) {
  const settings = useSharedSettings();

 //
  useLayoutEffect(() => {
    forwardRef.current.append(stage.finalBuffer);
    return () => stage.finalBuffer.remove();
  }, [stage]);

  return (
    <div
      className={clsx(
        styles.viewport,
        styles.renderingPreview,
        settings.background ? styles.canvasOutline : styles.alphaBackground,
      )}
      ref={forwardRef}>

        <CustomStageOverlay keyPressed={keyPressed}> {children} </CustomStageOverlay>
    </div>
  );
}
```

The hardes bit was probably trying to figure out how to get a reference to the stage and display the actual buffer on the [`CustomStageOverlay`](https://github.com/Gabryxx7/motion-canvas/blob/main/packages/ui/src/components/viewport/CustomStageOverlay.tsx):
```typescript
export interface CustomStageOverlayProps extends JSX.HTMLAttributes<HTMLDivElement> {
  children?: ComponentChildren;
  keyPressed?: any,
  isPlayer?: boolean
}
interface ProgressProps {
  completion: number;
}

export function CustomStageOverlay(props?: CustomStageOverlayProps) {
  const ref = useRef<HTMLDivElement>();
  const {keyPressed, children, isPlayer = false} = props;
  const [showOverlay, setShowOverlay] = useState(false);
  const {presenter, player} = useApplication();
  const state = useContext(ViewportContext);
  let paused = false;
  if(isPlayer){
    paused = usePlayerState().paused;
  }
  else{
    paused = useSubscribableValue(presenter.onInfoChanged).isWaiting
  }

// This is related to the my last issue regarding keybindings
useAction(moduleShortcuts.SHOW_OVERLAY, () => setShowOverlay(prev => !prev));

  return (
    <div 
    style={{aspectRatio: `${state.width / state.height}`}}
    {...props}
      className={clsx(viewportStyles.customStageOverlay, paused && viewportStyles.paused)}
      ref={ref}>
          <div
            className={clsx(viewportStyles.overlayContainer, !showOverlay && viewportStyles.hidden)}>
            {children}
          </div>
          {isPlayer ? <PlayerPauseOverlay /> : <PresenterPauseOverlay />}
          {/* { showProgress && <PresentationProgress /> } */}
          { !isPlayer && <PlaybackProgress /> }
        </div>
  );
}

export type {CustomStageOverlayProps as CustomStageOverlayPropsType}
export type CustomStageOverlayType = typeof CustomStageOverlay
```

The progress bars are fairly simple too. However I had to add a `sceneFramesRendered` to the presenter to get a somewhat correct completion that was not just given by the number of slides, and instead reflected what the playback and renderer would display.

```typescript
function ProgressBar({completion}: ProgressProps) {
  return <div className={clsx(viewportStyles.overlayProgress)}>
  <div className={viewportStyles.progress}>
    <div
      className={viewportStyles.progressFill}
      style={{width: `${completion * 100}%`}}
    />
  </div>
      </div>
}

function PlaybackProgress() {
  const {presenter} = useApplication();
  const presenterInfo = useSubscribableValue(presenter.onInfoChanged)
  return <ProgressBar completion={presenterInfo.sceneFramesRendered/presenterInfo.videoDuration} />
}

function PresentationProgress() {
  const {presenter} = useApplication();
  const presenterInfo = useSubscribableValue(presenter.onInfoChanged)
  return <ProgressBar completion={presenterInfo.index/presenterInfo.count} />
}

export function PlayerPauseOverlay(){
  const {paused} = usePlayerState();
  return(<IconButton className={clsx(viewportStyles.pauseIcon, paused && viewportStyles.hidden)}>
    <Pause />
  </IconButton>)
}

export function PresenterPauseOverlay(){
  const {presenter} = useApplication();
  const info = useSubscribableValue(presenter.onInfoChanged);
  return(<IconButton className={clsx(viewportStyles.pauseIcon, info.isWaiting && viewportStyles.hidden)}>
    <Pause />
  </IconButton>)
}
```

This new component can also be easily added to the player in the [`PreviewStage`](https://github.com/Gabryxx7/motion-canvas/blob/main/packages/ui/src/components/viewport/PreviewStage.tsx):
```typescript
...
  return <div ref={ref} {...props} >
       <CustomStageOverlay 
         style={{
         aspectRatio: 'unset',
         width: '100%',
         height: '100%'}}
         isPlayer={true}/>
     </div>;
}
```

The `scss` is nothing crazy, it is just making sure that the overlayed div scales up and down with the screen size, staying on top of the canvas correctly even when the default resolution of 1080p changes:

```scss

.customStageOverlay{
  position: absolute;
  display: flex;
  flex-direction: column;
  justify-content: flex-end;
  align-items: center;
  width: 100%;
  aspect-ratio: calc(16/9);
  color: #ffffff52;
  overflow: hidden;
  opacity: 1;
  .overlayContainer{
    padding: 0.5rem;
    overflow: hidden;
    opacity: 1;
    max-height: 100%;
    transform: translateY(0);
    transition: opacity .3s ease-out,max-height .8s ease-out, transform .1s ease-in;
    &.hidden{
      opacity: 0;
      max-height: 0%;
      transform: translateY(200%);
      transition: opacity .3s ease-out,max-height .8s ease-out, transform .1s ease-in;
    }
    .controls{
      display: flex;
      background-color: color-mix(in srgb, var(--surface-color) 70%, transparent);
      backdrop-filter: blur(3px);
      border-radius: var(--radius);
      padding: 1rem;
    }
  }


  .overlayProgress{
    width: 100%;
    height: 2px;
    .progress {
      transition: all 0.8s ease-out;
      height: 100%;
      background-color: transparent;
    }
    
    .progressFill {
      transition: all 0.8s ease-out;
      height: 2px;
      background-color: var(--theme);
      opacity: 0.9;
    }
  }
  .pauseIcon{
    align-self: flex-end;
    transition: all 0.8s ease-out;
    opacity: 0;
    svg{
      width: 1.5rem;
      height: 1.5rem;
      filter: drop-shadow(0.05rem 0.3rem 0.2rem rgba(0, 0, 0, 0.3));
      color: #cccccc;
    }
  }
  &.paused{
    .progressFill {
      height: 1.5px;
      transition: all 0.8s ease-out;
      opacity: 0.4;
    }
    .pauseIcon{
      transition: all 0.8s ease-out;
      opacity: 0.7;
      svg{
        width: 1.5rem;
        height: 1.5rem;
        filter: drop-shadow(0.05rem 0.3rem 0.2rem rgba(0, 0, 0, 0.3));
        color: #cccccc;
      }
    }
    
  }
```
**Considered alternatives**
I actually did try to add a pause button/icon via scenes and projects but there is no actual correct way to handle that within the scene itself. So I opted for an HTML overlay that hooks onto the presenter state.

This is what it ended up looking like (This is in full-screen presentation mode):
![image](https://github.com/motion-canvas/motion-canvas/assets/6282055/ce14faef-357f-402f-9001-c7e923c2d164)

The overlay can also be seen in the viewport playback, but I removed the progressbar there since it is already present.
